# Generated by Django 4.0.1 on 2022-01-16 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=20)),
                ('car_capacity', models.IntegerField()),
                ('real_name', models.CharField(max_length=50)),
                ('licence_number', models.CharField(max_length=50)),
                ('special_info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('passenger_num', models.IntegerField(default=0)),
                ('destination', models.CharField(max_length=100)),
                ('arrival_time', models.DateTimeField()),
                ('is_exclusive', models.BooleanField()),
                ('sharer_num', models.IntegerField()),
                ('special_info', models.CharField(max_length=200)),
                ('confirm_time', models.DateTimeField()),
                ('complete_time', models.DateTimeField()),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.BooleanField()),
                ('request_time', models.DateTimeField()),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ride')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('is_driver', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user'),
        ),
    ]
