# Generated by Django 4.0.1 on 2022-01-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_ride_complete_time_alter_ride_confirm_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='car_type',
            field=models.CharField(default='Unspecified', max_length=20),
        ),
        migrations.AlterField(
            model_name='ride',
            name='special_info',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
