# Generated by Django 4.0.1 on 2022-01-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_ride_car_type_alter_ride_special_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='passenger_num',
            field=models.IntegerField(default=0),
        ),
    ]
