# Generated by Django 4.0.1 on 2022-01-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_transaction_passenger_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='number_of_incomplete_orders',
            field=models.IntegerField(default=0),
        ),
    ]
